version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./public:/var/www/html
      - ./assets:/var/www/html/assets
      - ./config:/var/www/html/config
      - ./models:/var/www/html/models
      - ./controllers:/var/www/html/controllers
      - ./vendor:/var/www/html/vendor
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_platform
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpassword
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
